export const eslintConfig = () => {
  return [
    {
      name: 'yungando/eslint',
      /// keep-sorted
      rules: {
        'array-callback-return': ['error', { allowImplicit: true }],
        'arrow-body-style': ['error', 'as-needed'],
        'class-methods-use-this': 'error',
        'consistent-return': 'error',
        'default-case': 'error',
        'default-param-last': 'error',
        'for-direction': 'error',
        'getter-return': 'error',
        'grouped-accessor-pairs': 'error',
        'guard-for-in': 'error',
        'max-classes-per-file': ['error', 1],
        'new-cap': ['error', { capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'], properties: false }],
        'no-bitwise': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': 'error',
        'no-constructor-return': 'error',
        'no-dupe-else-if': 'error',
        'no-else-return': ['error', { allowElseIf: false }],
        'no-empty-function': ['error', { allow: ['arrowFunctions', 'methods'] }],
        'no-empty-static-block': 'error',
        'no-extra-label': 'error',
        'no-inner-declarations': 'error',
        'no-invalid-this': 'error',
        'no-label-var': 'error',
        'no-lonely-if': 'error',
        'no-loop-func': 'error',
        'no-multi-assign': 'error',
        'no-nested-ternary': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-object-constructor': 'error',
        'no-param-reassign': ['error', { props: true }],
        'no-plusplus': 'error',
        'no-promise-executor-return': 'error',
        'no-restricted-exports': ['error', { restrictedNamedExports: ['default', 'then'] }],
        'no-restricted-syntax': ['error', 'DebuggerStatement', 'LabeledStatement', 'WithStatement'],
        'no-return-assign': ['error', 'always'],
        'no-script-url': 'error',
        'no-setter-return': 'error',
        'no-shadow': 'error',
        'no-unassigned-vars': 'error',
        'no-underscore-dangle': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-private-class-members': 'error',
        'no-unused-vars': ['error', { vars: 'all', args: 'after-used', caughtErrors: 'all' }],
        'no-useless-assignment': 'error',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-void': 'error',
        'one-var': ['error', 'never'],
        'operator-assignment': 'error',
        'prefer-destructuring': ['error', { VariableDeclarator: { array: false, object: true }, AssignmentExpression: { array: true, object: false } }, { enforceForRenamedProperties: false }],
        'prefer-numeric-literals': 'error',
        'prefer-object-has-own': 'error',
        'prefer-object-spread': 'error',
        'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
        'preserve-caught-error': 'error',
        'require-yield': 'error',
        camelcase: ['error', { properties: 'never' }],
        curly: ['error', 'multi-line'],
        radix: 'error',
      },
    },
  ];
};
